language: csharp
dist: trusty
script:
  - ./build.sh
# addons: 
#   apt:
#     packages:
#     - gettext
#     - libcurl4-openssl-dev
#     - libicu-dev
#     - libssl-dev
#     - libunwind8
#     - zlib1g
env:
  - CLI_VERSION=latest
install:  
  # - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  # - export DOTNET_CLI_TELEMETRY_OPTOUT=true
  # - curl -sSL https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  # - export PATH="$DOTNET_INSTALL_DIR:$PATH" 
cache:
  directories:
    - tools